# Generated by Django 3.0.5 on 2021-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('publication_title', models.CharField(max_length=400)),
                ('publication_number', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('match', models.CharField(max_length=300)),
                ('type_organization', models.CharField(max_length=50)),
            ],
        ),
    ]
